---
name: CMS

on:
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: cms
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: Lint code
        run: bundle exec standardrb --format RuboCop::Formatter::JUnitFormatter --out tmp/standard/output.xml
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: actions/upload-artifact@v4
        with:
          name: standardrb
          path: ${{ env.WORKING_DIRECTORY }}/tmp/standard/output.xml

  test:
    runs-on: ubuntu-latest
    env:
      WORKING_DIRECTORY: cms
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.0
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - name: Run tests
        run: bundle exec rake test A="--junit"
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: actions/upload-artifact@v4
        with:
          name: test
          path: ${{ env.WORKING_DIRECTORY }}/report.xml

  publish-results:
    needs:
      - lint
      - test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: artifacts/standardrb/output.xml
          check_name: "Lint results 👮‍♂️"
      - uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: artifacts/test/report.xml
          check_name: "Test results"
